#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path

def build(bld):
    #warning: order matters (pcre2plus should be before pcre2)
    conan_deps = ['pcre2plus', 'pcre2']

    #Compile an executable from cpp files on source dir
    bld.program(
        target   = 'program',
        source   = ['main.cpp'],
        includes = ['.'],
        use      = conan_deps)

    bld.program(
        target   = 'regextest',
        source   = ['regextest.cpp'],
        linkflags=['-rdynamic'],
        includes = ['.'],
        use      = conan_deps)



def glob(bld, *k, **kw):
    '''Helper to execute an ant_glob search.
        See documentation at: https://waf.io/apidocs/Node.html?#waflib.Node.Node.ant_glob
    '''

    return bld.path.ant_glob(*k, **kw)
