#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path

def build(bld):
    #warning: order matters (pcre2plus should be before pcre2)
    conan_deps = ['pcre2plus', 'pcre2', 'commonex']

    bld(
        name            = 'cppgherkin',
        includes        = ['.'],
        export_includes = ['.'],
        use             = conan_deps
    )

    bld.recurse('examples')

    if bld.env.build_tests:
        bld.recurse('test')

def glob(bld, *k, **kw):
    '''Helper to execute an ant_glob search.
        See documentation at: https://waf.io/apidocs/Node.html?#waflib.Node.Node.ant_glob
    '''

    return bld.path.ant_glob(*k, **kw)
